apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script-cm
  namespace: {{NAMESPACE}}
data:
  setup-and-corrupt.sh: |
    {{SETUP_SCRIPT_CODE}}
  corruptor.yaml: |
    {{CORRUPTOR_YAML_CODE}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-and-corrupt
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      serviceAccountName: cp-recovery-setup-sa
      containers:
      - name: setup
        image: google/cloud-sdk:slim
        command: ["/bin/bash", "/scripts/setup-and-corrupt.sh"]
        env:
        - name: NAMESPACE
          value: "{{NAMESPACE}}"
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: scripts-volume
        configMap:
          name: setup-script-cm
